### PR TITLE
[Merged by Bors] - Enable Prometheus scraping

### LINKED ISSUE #307: Enable Prometheus scraping
Annotation `prometheus.io/scrape: "true"` should be added to role services

### PR DESCRIPTION
**Pull request by teozkr**
## Description

Fixes #307 

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by teozkr** [comment]
Hm, looks like the metrics endpoint exposed is actually børked, moving this to in progress for now.

**Comment by teozkr** [comment]
Fixed.

**Review by razvan — APPROVED** [review]
lgtm

**Comment by lfrancke** [comment]
Nooo! There is atypo in here. It says ZooKeeper

**Comment by teozkr** [comment]
Oops.

**Pull request closed without merging**
