### PR TITLE
Updating version in upgrade test

### PR DESCRIPTION
**Pull request by Maleware**
# Description

Changes `stackable0.0.0-dev` to `stackable24.7.0` in upgrade-zookeeper

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Comment by NickLarsenNZ** [comment]
This might be something that needs to be caught in: https://github.com/stackabletech/stackable-utils/blob/main/release/create-release-tag.sh

**Comment by maltesander** [comment]
Yeah and there are more left overs https://github.com/stackabletech/kafka-operator/blob/a07b221e2cc6cfd61a629634b1e2a19b1b872d0a/tests/templates/kuttl/logging/05-install-kafka-test-runner.yaml#L20 (and more)

**Comment by adwk67** [comment]
This PR was necessary as it checks a *label* (which causes the test to fail if not updated to the release version).

**Review by adwk67 — APPROVED** [review]
LGTM

**Pull request merged**
