### PR TITLE
[Merged by Bors] - Operator-rs: 0.8 -> 0.10

### PR DESCRIPTION
**Pull request by teozkr**
## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by teozkr** [comment]
Updated to operator-rs 0.10.0

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request closed without merging**
