### PR TITLE
Remove OPA requirement so that the 'quickstart' is simplified

### PR DESCRIPTION
**Pull request by pipern**
Other parts of the documentation do not mention OPA, so removing the implicit requirement on OPA from the example KafkaCluster

ref: #153

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Review by maltesander — COMMENTED** [review]
Thank you. Can we have both cases? The current one without OPA and one with OPA?

**Comment by pipern** [comment]
> Thank you. Can we have both cases? The current one without OPA and one with OPA?

Done. Sorry for small noise with multiple pushes, I wanted to avoid the trailing whitespace being changed.

**Comment by maltesander** [comment]
No worries and thank you. We need to adapt the GitHub actions a little (which we will do the next days hopefully) to have this merged from a fork (we did it last time for zookeeper already). If you are ok with it, i approve now and will merge it as soon as the actions are adapted?

**Review by soenkeliebau — APPROVED** [review]
LGTM

**Pull request merged**
